services:
  # SERVICIO DE BASE DE DATOS (MariaDB)
  db:
    image: speicon1911/base-de-datos-mariadb:mariaDB
    container_name: autolink-db-pruebas
    restart: always
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=secreta
      - MYSQL_DATABASE=autolink
    volumes:
      - mariadb_data:/var/lib/mysql

  # SERVICIO DE ADMINISTRACIÓN (phpMyAdmin)
  phpmyadmin:
    image: speicon1911/base-de-datos-mariadb:phpMyAdmin
    container_name: autolink-pma-pruebas
    restart: always
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
    depends_on:
      - db
volumes:
  mariadb_data:
