services:
  # SERVICIO DE BASE DE DATOS (MariaDB)
  db:
    image: speicon1911/autolink-tfg:mariadb
    container_name: autolink-db
    restart: always
    # Blindado localmente. Solo es accesible internamente.
    expose:
      - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
      - mariadb_data:/var/lib/mysql

  # SERVICIO DE ADMINISTRACIÓN (phpMyAdmin)
  phpmyadmin:
    image: speicon1911/autolink-tfg:phpmyadmin
    container_name: autolink-pma
    restart: always
    expose:
      - "80"
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
      - PMA_ABSOLUTE_URI=http://localhost/admin-pma/
    depends_on:
      - db

  # SERVICIO BACKEND (Spring Boot API) - CONSTRUIDO DESDE TU CARPETA LOCAL
  backend:
    build:
      context: ./autolink-backend
      dockerfile: Dockerfile
    container_name: autolink-backend
    restart: always
    expose:
      - "8082"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://db:3306/${MYSQL_DATABASE}?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - MAIL_HOST=${MAIL_HOST}
      - MAIL_PORT=${MAIL_PORT}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - CORS_ALLOWED_ORIGIN=${CORS_ALLOWED_ORIGIN} # Ej: http://localhost
    depends_on:
      - db

  # SERVICIO FRONTEND (Angular SSR) - CONSTRUIDO DESDE TU CARPETA LOCAL
  frontend:
    build:
      context: ./autolink-frontend
      dockerfile: Dockerfile
    container_name: autolink-frontend
    restart: always
    expose:
      - "4000"
    environment:
      - PORT=4000
    depends_on:
      - backend

  # SERVICIO: NGINX (PROXY INVERSO LOCAL)
  nginx:
    image: nginx:alpine
    container_name: autolink-nginx
    restart: always
    ports:
      - "80:80" # Mapea el puerto local 80 al contenedor
    volumes:
      # Mapeamos la configuración de Nginx exclusiva para localhost (sin SSL)
      - ./nginx/nginx.local.conf.template:/etc/nginx/templates/default.conf.template:ro
    environment:
      - PMA_SECURITY_KEY=${PMA_SECURITY_KEY}
    depends_on:
      - frontend
      - backend
      - phpmyadmin

volumes:
  mariadb_data:
